fix: provide more accurate error for invalid fragment spread
wundergraph/graphql-go-tools pull request #538
Opened 2023-06-05 16:23 UTC by Aenimus

Spreading a fragment on an invalid type should provide a more accurate error.

Also revert an accidental change of port for the federation example.

2023-06-05 16:45 UTC, devsergiy approved these changes

2023-06-05 16:46 UTC, devsergiy requested changes
tests are failing

2023-06-05 19:21 UTC, fiam commented on pkg/astvalidation/operation_rule_fragments.go
> +	defer func() {
Would it be possible to avoid causing the panic without too big of a refactor?

2023-06-06 10:23 UTC, devsergiy approved these changes

2023-06-06 11:33 UTC, fiam approved these changes
LGTM

2023-06-06 11:36 UTC, merged