fix: fixes for interfaces, unions, and required types
wundergraph/graphql-go-tools pull request #541
Opened 2023-06-12 01:22 UTC by Aenimus

2023-06-12 01:25 UTC, Aenimus commented on go.mod
These updated automatically. Are we safe to update?

2023-06-12 01:26 UTC, Aenimus commented on pkg/engine/datasource/graphql_datasource/graphql_datasource.go
>  		return
Adding typename here just created duplicate typenames.

2023-06-12 01:27 UTC, Aenimus commented on pkg/engine/datasource/graphql_datasource/graphql_datasource.go
> +		// Adding the typename to abstract (unions and interfaces) types is handled elsewhere
`__typename` is handled properly when creating selection sets.

2023-06-12 11:34 UTC, Aenimus commented on pkg/engine/plan/plan.go
> +	queriedFieldPaths map[string]struct{}
seleted*

2023-06-12 11:55 UTC, Aenimus commented on pkg/engine/plan/plan.go
> +	if !exists || !node.Kind.IsAbstractType() {
Add comment about union memebers

2023-06-12 11:57 UTC, Aenimus commented on pkg/engine/plan/plan.go
> +		if plannerConfig.hasPath(parent) {
rename current and parent to -Path

2023-06-12 11:59 UTC, Aenimus commented on pkg/engine/plan/plan.go
> +func (c *configurationVisitor) wasPathAddedForUnion(fieldRef, plannerIndex int, currentPath string) (pathAdded bool) {
rename method

2023-06-12 12:07 UTC, Aenimus commented on pkg/testing/federationtesting/federation_integration_test.go
> +	t.Run("Complex nesting", func(t *testing.T) {
comment about duplicated fields

2023-06-12 12:12 UTC, Aenimus commented on pkg/engine/plan/plan.go
> +		// If a field was not explicitly queried, skip it
selected

2023-06-15 20:26 UTC, devsergiy requested changes

2023-06-15 20:26 UTC, devsergiy commented on pkg/engine/plan/plan.go
> +	for _, path := range c.planners[plannerRef].paths {
probably could be replaced with
```go
c.planners[plannerRef].hasPath(parentPath)
```

2023-06-15 20:26 UTC, devsergiy commented on pkg/engine/plan/plan.go
> +		if c.addPlannerPathForChildOfAbstractParent(i, typeName, fieldName, parentPath, currentPath) {
`addPlannerPathForChildOfAbstractParent` has inside a check if planner has parentPath

It means this if could be moved into previous `if` like this

```go
if plannerConfig.hasPath(parentPath) {
	if plannerConfig.hasChildNode(typeName, fieldName) {
		// has parent path + has child node = child
		c.planners[i].paths = append(c.planners[i].paths, pathConfiguration{path: currentPath, shouldWalkFields: true})
		return
	}

	if pathAdded := c.addPlannerPathForUnionChildOfObjectParent(ref, i, currentPath); pathAdded {
		return
	}

	if pathAdded := c.addPlannerPathForChildOfAbstractParent(i, typeName, fieldName, parentPath, currentPath); pathAdded {
		return
	}
}
```

For verbosity we could also add such explicit check
```go
if pathAdded:= (); pathAdded {
}
```

2023-06-15 20:26 UTC, devsergiy commented on pkg/engine/plan/plan.go
> +func (c *configurationVisitor) addPlannerPathForChildOfAbstractParent(
in case we will remove checking for presence of parentPath we could remove corresponding argument

also in `addPlannerPathForUnionChildOfObjectParent` you have a planner index with name `plannerIndex`, it will be better, cause we use ref more in the ast

2023-06-15 20:26 UTC, devsergiy commented on pkg/engine/plan/plan.go
> +	for _, path := range c.planners[plannerRef].paths {
or not needed at all

2023-06-15 20:30 UTC, devsergiy commented on pkg/engine/plan/plan.go
> +		// LeaveDocument uses this record to ensure only required fields that were not explicitly selected are skipped
this code is also responsive for field aliases, we could also mention it

and maybe provide some small code examples of what these additions doing
e.g. what fields selected and what will be included and what is not

2023-06-21 10:12 UTC, devsergiy approved these changes

2023-06-21 10:17 UTC, merged